<?xml version="1.0"?>
<testsuite name='osmo-ttcn3-hacks/sysinfo' tests='22' failures='3' errors='16' skipped='0' inconc='0' time='MASKED'>
  <testcase classname='Test' name='TC_si1' time='MASKED'/>
  <testcase classname='Test' name='TC_telnet' time='MASKED'/>
  <testcase classname='Test' name='TC_si_default' time='MASKED'>
    <failure type='fail-verdict'>No SI messages for TC=0!

    </failure>
  </testcase>
  <testcase classname='Test' name='TC_si_sched_2bis' time='MASKED'>
    <failure type='fail-verdict'>No SI messages for TC=0!

    </failure>
  </testcase>
  <testcase classname='Test' name='TC_si_sched_2ter' time='MASKED'>
    <failure type='fail-verdict'>No SI messages for TC=0!

    </failure>
  </testcase>
  <testcase classname='Test' name='TC_si_sched_2ter_2bis' time='MASKED'>
    <error type='DTE'>Test.ttcn:MASKED: Dynamic test case error: testcase.stop</error>
  </testcase>
  <testcase classname='Test' name='TC_si_sched_2quater' time='MASKED'/>
  <testcase classname='Test' name='TC_si_sched_13' time='MASKED'>
    <error type='DTE'>Test.ttcn:MASKED: Dynamic test case error: testcase.stop</error>
  </testcase>
  <testcase classname='Test' name='TC_si_sched_13_2bis_2ter_2quater' time='MASKED'>
    <error type='DTE'>Test.ttcn:MASKED: Dynamic test case error: testcase.stop</error>
  </testcase>
  <testcase classname='Test' name='TC_neci' time='MASKED'>
    <error type='DTE'>Test.ttcn:MASKED: Dynamic test case error: testcase.stop</error>
  </testcase>
  <testcase classname='Test' name='TC_cell_resel_hyst' time='MASKED'>
    <error type='DTE'>Test.ttcn:MASKED: Dynamic test case error: testcase.stop</error>
  </testcase>
  <testcase classname='Test' name='TC_rxlev_acc_min' time='MASKED'>
    <error type='DTE'>Test.ttcn:MASKED: Dynamic test case error: testcase.stop</error>
  </testcase>
  <testcase classname='Test' name='TC_cellid' time='MASKED'>
    <error type='DTE'>Test.ttcn:MASKED: Dynamic test case error: testcase.stop</error>
  </testcase>
  <testcase classname='Test' name='TC_lac' time='MASKED'>
    <error type='DTE'>Test.ttcn:MASKED: Dynamic test case error: testcase.stop</error>
  </testcase>
  <testcase classname='Test' name='TC_rach_tx_int' time='MASKED'>
    <error type='DTE'>Test.ttcn:MASKED: Dynamic test case error: testcase.stop</error>
  </testcase>
  <testcase classname='Test' name='TC_rach_max_tx' time='MASKED'>
    <error type='DTE'>Test.ttcn:MASKED: Dynamic test case error: testcase.stop</error>
  </testcase>
  <testcase classname='Test' name='TC_attach' time='MASKED'>
    <error type='DTE'>Test.ttcn:MASKED: Dynamic test case error: testcase.stop</error>
  </testcase>
  <testcase classname='Test' name='TC_dtx_ul' time='MASKED'>
    <error type='DTE'>Test.ttcn:MASKED: Dynamic test case error: testcase.stop</error>
  </testcase>
  <testcase classname='Test' name='TC_emerg_allowed' time='MASKED'>
    <error type='DTE'>Test.ttcn:MASKED: Dynamic test case error: testcase.stop</error>
  </testcase>
  <testcase classname='Test' name='TC_bs_pa_mfrms' time='MASKED'>
    <error type='DTE'>Test.ttcn:MASKED: Dynamic test case error: testcase.stop</error>
  </testcase>
  <testcase classname='Test' name='TC_bs_ag_blks_res' time='MASKED'>
    <error type='DTE'>Test.ttcn:MASKED: Dynamic test case error: testcase.stop</error>
  </testcase>
  <testcase classname='Test' name='TC_radio_link_timeout' time='MASKED'>
    <error type='DTE'>Test.ttcn:MASKED: Dynamic test case error: testcase.stop</error>
  </testcase>
</testsuite>
